### ISSUE TITLE
Installation issues on windows with anaconda

### ISSUE THREAD

**Issue by MartijnGosgens** [mapequation/infomap#141]
Hi,

I am trying to install infomap via anaconda on Windows 10. I started by running `conda skeleton pypi infomap`, which completes without errors. Then I call `conda build infomap`, which gives the error below. Previously I had the issue that windows was unable to find the C compiler (`cl.exe`) which was resolved by adding the folder to the PATH environment variable.

Now this C compiler gives the error that it cannot find some io.h file.

I think the issue lies in the fact that it calls `set "CMAKE_GENERATOR=Visual Studio 14 2015 Win64"` and assumes Visual Studio 14 in a few other places as well.

Could anyone help me with this installation issue?

Thanks in advance,
Martijn

```

(base) C:\>conda build infomap
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for infomap
INFO:conda_build.metadata:Attempting to finalize metadata for infomap
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
BUILD START: ['infomap-1.1.3-py37_0.tar.bz2']
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\ProgramData\Anaconda3\conda-bld\infomap_1595497087882\_h_env


The following NEW packages will be INSTALLED:

    ca-certificates: 2020.6.24-0
    certifi:         2020.6.20-py37_0
    openssl:         1.1.1g-he774522_0
    pip:             20.1.1-py37_1
    python:          3.7.7-h81c818b_4
    setuptools:      49.2.0-py37_0
    sqlite:          3.32.3-h2a8f88b_0
    vc:              14.1-h0510ff6_4
    vs2015_runtime:  14.16.27012-hf0eaf9b_3
    wheel:           0.34.2-py37_0
    wincertstore:    0.2-py37_0
    zlib:            1.2.11-h62dcd97_4

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Source cache directory is: C:\ProgramData\Anaconda3\conda-bld\src_cache
INFO:conda_build.source:Source cache directory is: C:\ProgramData\Anaconda3\conda-bld\src_cache
INFO conda_build.source:download_to_cache(43): Source cache directory is: C:\ProgramData\Anaconda3\conda-bld\src_cache
Found source in cache: infomap-1.1.3_8fc1ba9d2c.tar.gz
INFO:conda_build.source:Found source in cache: infomap-1.1.3_8fc1ba9d2c.tar.gz
INFO conda_build.source:download_to_cache(63): Found source in cache: infomap-1.1.3_8fc1ba9d2c.tar.gz
Extracting download
source tree in: C:\ProgramData\Anaconda3\conda-bld\infomap_1595497087882\work
Using legacy MSVC compiler setup.  This will be removed in conda-build 4.0. If this recipe does not use a compiler, this message is safe to ignore.  Otherwise, use {{compiler('<language>')}} jinja2 in requirements/build.
WARNING:conda_build.windows:Using legacy MSVC compiler setup.  This will be removed in conda-build 4.0. If this recipe does not use a compiler, this message is safe to ignore.  Otherwise, use {{compiler('<language>')}} jinja2 in requirements/build.
WARNING conda_build.windows:msvc_env_cmd(91): Using legacy MSVC compiler setup.  This will be removed in conda-build 4.0. If this recipe does not use a compiler, this message is safe to ignore.  Otherwise, use {{compiler('<language>')}} jinja2 in requirements/build.
Rewriting env in output: {'BUILD_PREFIX': 'C:\\ProgramData\\Anaconda3\\conda-bld\\infomap_1595497087882\\_build_env',
 'PREFIX': 'C:\\ProgramData\\Anaconda3\\conda-bld\\infomap_1595497087882\\_h_env',
 'SRC_DIR': 'C:\\ProgramData\\Anaconda3\\conda-bld\\infomap_1595497087882\\work'}

(base) %SRC_DIR%>IF "" == "" (call %SRC_DIR%\build_env_setup.bat )

(base) %SRC_DIR%>set "CONDA_BUILD=1"

(base) %SRC_DIR%>set "PYTHONNOUSERSITE=1"

(base) %SRC_DIR%>set "CONDA_DEFAULT_ENV=%PREFIX%"

(base) %SRC_DIR%>set "ARCH=64"

(base) %SRC_DIR%>set "PREFIX=%PREFIX%"

(base) %SRC_DIR%>set "BUILD_PREFIX=%BUILD_PREFIX%"

(base) %SRC_DIR%>set "SYS_PREFIX=C:\ProgramData\Anaconda3"

(base) %SRC_DIR%>set "SYS_PYTHON=C:\ProgramData\Anaconda3\python.exe"

(base) %SRC_DIR%>set "SUBDIR=win-64"

(base) %SRC_DIR%>set "SRC_DIR=%SRC_DIR%"

(base) %SRC_DIR%>set "ROOT=C:\ProgramData\Anaconda3"

(base) %SRC_DIR%>set "CONDA_PY=37"

(base) %SRC_DIR%>set "PY3K=1"

(base) %SRC_DIR%>set "PY_VER=3.7"

(base) %SRC_DIR%>set "STDLIB_DIR=%PREFIX%\Lib"

(base) %SRC_DIR%>set "SP_DIR=%PREFIX%\Lib\site-packages"

(base) %SRC_DIR%>set "PYTHON=%PREFIX%\python.exe"

(base) %SRC_DIR%>set "NPY_VER=1.11"

(base) %SRC_DIR%>set "CONDA_NPY=1.11"

(base) %SRC_DIR%>set "NPY_DISTUTILS_APPEND_FLAGS=1"

(base) %SRC_DIR%>set "PERL_VER=5.26"

(base) %SRC_DIR%>set "CONDA_PERL=5.26.0"

(base) %SRC_DIR%>set "LUA_VER=5"

(base) %SRC_DIR%>set "CONDA_LUA=5"

(base) %SRC_DIR%>set "R_VER=3.4"

(base) %SRC_DIR%>set "CONDA_R=3.4"

(base) %SRC_DIR%>set "PKG_NAME=infomap"

(base) %SRC_DIR%>set "PKG_VERSION=1.1.3"

(base) %SRC_DIR%>set "PKG_BUILDNUM=0"

(base) %SRC_DIR%>set "PKG_BUILD_STRING=placeholder"

(base) %SRC_DIR%>set "PKG_HASH=1234567"

(base) %SRC_DIR%>set "RECIPE_DIR=C:\infomap"

(base) %SRC_DIR%>set "CPU_COUNT=12"

(base) %SRC_DIR%>set "SHLIB_EXT=.dll"

(base) %SRC_DIR%>set "PATH=%BUILD_PREFIX%;%BUILD_PREFIX%\Library\mingw-w64\bin;%BUILD_PREFIX%\Library\usr\bin;;%BUILD_PREFIX%\Library\bin;%BUILD_PREFIX%\Scripts;%BUILD_PREFIX%\Scripts;%PREFIX%;%PREFIX%\Library\mingw-w64\bin;%PREFIX%\Library\usr\bin;;%PREFIX%\Library\bin;%PREFIX%\Scripts;%PREFIX%\Scripts;C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\Library\mingw-w64\bin;C:\ProgramData\Anaconda3\Library\usr\bin;C:\ProgramData\Anaconda3\Library\bin;C:\ProgramData\Anaconda3\Scripts;C:\ProgramData\Anaconda3\bin;C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\Library\mingw-w64\bin;C:\ProgramData\Anaconda3\Library\usr\bin;C:\ProgramData\Anaconda3\Library\bin;C:\ProgramData\Anaconda3\Scripts;C:\ProgramData\Anaconda3\bin;C:\ProgramData\Anaconda3\condabin;C:\gurobi902\win64\bin;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0;C:\windows\System32\OpenSSH;C:\Program Files (x86)\PuTTY;C:\Program Files\MiKTeX 2.9\miktex\bin\x64;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\Program Files\Git\cmd;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\bin\Hostx64\x64;C:\Users\s147569\AppData\Local\Microsoft\WindowsApps;C:\Users\s147569\AppData\Local\atom\bin;C:\Pyton27;."

(base) %SRC_DIR%>set "SCRIPTS=%PREFIX%\Scripts"

(base) %SRC_DIR%>set "LIBRARY_PREFIX=%PREFIX%\Library"

(base) %SRC_DIR%>set "LIBRARY_BIN=%PREFIX%\Library\bin"

(base) %SRC_DIR%>set "LIBRARY_INC=%PREFIX%\Library\include"

(base) %SRC_DIR%>set "LIBRARY_LIB=%PREFIX%\Library\lib"

(base) %SRC_DIR%>set "CYGWIN_PREFIX=/cygdrive/c/ProgramData/Anaconda3/conda-bld/infomap_1595497087882/_h_env"

(base) %SRC_DIR%>set "ALLUSERSPROFILE=C:\ProgramData"

(base) %SRC_DIR%>set "APPDATA=C:\Users\s147569\AppData\Roaming"

(base) %SRC_DIR%>set "CommonProgramFiles=C:\Program Files\Common Files"

(base) %SRC_DIR%>set "CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files"

(base) %SRC_DIR%>set "CommonProgramW6432=C:\Program Files\Common Files"

(base) %SRC_DIR%>set "COMPUTERNAME=TUE018360"

(base) %SRC_DIR%>set "ComSpec=C:\windows\system32\cmd.exe"

(base) %SRC_DIR%>set "HOMEDRIVE=G:"

(base) %SRC_DIR%>set "HOMEPATH=\"

(base) %SRC_DIR%>set "LOCALAPPDATA=C:\Users\s147569\AppData\Local"

(base) %SRC_DIR%>set "LOGONSERVER=\\CAMPUSDC4"

(base) %SRC_DIR%>set "NUMBER_OF_PROCESSORS=12"

(base) %SRC_DIR%>set "PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC"

(base) %SRC_DIR%>set "ProgramData=C:\ProgramData"

(base) %SRC_DIR%>set "ProgramFiles=C:\Program Files"

(base) %SRC_DIR%>set "ProgramFiles(x86)=C:\Program Files (x86)"

(base) %SRC_DIR%>set "ProgramW6432=C:\Program Files"

(base) %SRC_DIR%>set "PROMPT=(base) $P$G"

(base) %SRC_DIR%>set "PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\windows\system32\WindowsPowerShell\v1.0\Modules"

(base) %SRC_DIR%>set "PUBLIC=C:\Users\Public"

(base) %SRC_DIR%>set "SystemDrive=C:"

(base) %SRC_DIR%>set "SystemRoot=C:\windows"

(base) %SRC_DIR%>set "TEMP=C:\Users\s147569\AppData\Local\Temp"

(base) %SRC_DIR%>set "TMP=C:\Users\s147569\AppData\Local\Temp"

(base) %SRC_DIR%>set "USERDOMAIN=TUE"

(base) %SRC_DIR%>set "USERNAME=s147569"

(base) %SRC_DIR%>set "USERPROFILE=C:\Users\s147569"

(base) %SRC_DIR%>set "windir=C:\windows"

(base) %SRC_DIR%>set "PROCESSOR_ARCHITECTURE=AMD64"

(base) %SRC_DIR%>set "PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 158 Stepping 10, GenuineIntel"

(base) %SRC_DIR%>set "BUILD=amd64-pc-windows-19.0.0"

(base) %SRC_DIR%>set "r_base=3.4"

(base) %SRC_DIR%>set "cpu_optimization_target=nocona"

(base) %SRC_DIR%>set "cran_mirror=https://cran.r-project.org"

(base) %SRC_DIR%>set "target_platform=win-64"

(base) %SRC_DIR%>set "c_compiler=vs2017"

(base) %SRC_DIR%>set "cxx_compiler=vs2017"

(base) %SRC_DIR%>set "fortran_compiler=gfortran"

(base) %SRC_DIR%>set "vc=14"

(base) %SRC_DIR%>set "ignore_build_only_deps={'numpy', 'python'}"

(base) %SRC_DIR%>set "extend_keys={'extend_keys', 'ignore_version', 'ignore_build_only_deps', 'pin_run_as_build'}"

(base) %SRC_DIR%>set "pin_run_as_build=OrderedDict([('python', {'min_pin': 'x.x', 'max_pin': 'x.x'}), ('r-base', {'min_pin': 'x.x', 'max_pin': 'x.x'})])"

(base) %SRC_DIR%>set "CONDA_BUILD_STATE=BUILD"

(base) %SRC_DIR%>set "PIP_NO_BUILD_ISOLATION=False"

(base) %SRC_DIR%>set "PIP_NO_DEPENDENCIES=True"

(base) %SRC_DIR%>set "PIP_IGNORE_INSTALLED=True"

(base) %SRC_DIR%>set "PIP_CACHE_DIR=C:\ProgramData\Anaconda3\conda-bld\infomap_1595497087882\pip_cache"

(base) %SRC_DIR%>set "PIP_NO_INDEX=True"

(base) %SRC_DIR%>set DISTUTILS_USE_SDK=1

(base) %SRC_DIR%>set MSSdk=1

(base) %SRC_DIR%>set PY_VCRUNTIME_REDIST=%PREFIX%\Library\bin\vcruntime140.dll

(base) %SRC_DIR%>set "VS_VERSION=14.0"

(base) %SRC_DIR%>set "VS_MAJOR=14"

(base) %SRC_DIR%>set "VS_YEAR=2015"

(base) %SRC_DIR%>set "CMAKE_GENERATOR=Visual Studio 14 2015 Win64"

(base) %SRC_DIR%>set "MSYS2_ARG_CONV_EXCL=/AI;/AL;/OUT;/out"

(base) %SRC_DIR%>set "MSYS2_ENV_CONV_EXCL=CL"

(base) %SRC_DIR%>call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
The system cannot find the path specified.

(base) %SRC_DIR%>set "INCLUDE=%PREFIX%\Library\include;"

(base) %SRC_DIR%>set "LIB=%PREFIX%\Library\lib;"

(base) %SRC_DIR%>call "C:\ProgramData\Anaconda3\Scripts\..\condabin\conda_hook.bat"

(base) %SRC_DIR%>call "C:\ProgramData\Anaconda3\Scripts\..\condabin\conda.bat" activate "%PREFIX%"

(%PREFIX%) %SRC_DIR%>call "C:\ProgramData\Anaconda3\Scripts\..\condabin\conda.bat" activate --stack "%BUILD_PREFIX%"
Not a conda environment: C:\ProgramData\Anaconda3\conda-bld\infomap_1595497087882\_build_env

(%PREFIX%) %SRC_DIR%>REM ===== end generated header =====

(%PREFIX%) %SRC_DIR%>%PREFIX%\python.exe -m pip install . -vv
Non-user install because user site-packages disabled
Ignoring indexes: https://pypi.org/simple
Created temporary directory: C:\Users\s147569\AppData\Local\Temp\pip-ephem-wheel-cache-m_br5kpa
Created temporary directory: C:\Users\s147569\AppData\Local\Temp\pip-req-tracker-3hlurgau
Initialized build tracking at C:\Users\s147569\AppData\Local\Temp\pip-req-tracker-3hlurgau
Created build tracker: C:\Users\s147569\AppData\Local\Temp\pip-req-tracker-3hlurgau
Entered build tracker: C:\Users\s147569\AppData\Local\Temp\pip-req-tracker-3hlurgau
Created temporary directory: C:\Users\s147569\AppData\Local\Temp\pip-install-2chwyw2r
Processing c:\programdata\anaconda3\conda-bld\infomap_1595497087882\work
  Created temporary directory: C:\Users\s147569\AppData\Local\Temp\pip-req-build-zjneawaa
  Added file:///C:/ProgramData/Anaconda3/conda-bld/infomap_1595497087882/work to build tracker 'C:\\Users\\s147569\\AppData\\Local\\Temp\\pip-req-tracker-3hlurgau'
    Running setup.py (path:C:\Users\s147569\AppData\Local\Temp\pip-req-build-zjneawaa\setup.py) egg_info for package from file:///C:/ProgramData/Anaconda3/conda-bld/infomap_1595497087882/work
    Running command python setup.py egg_info
    Created temporary directory: C:\Users\s147569\AppData\Local\Temp\pip-pip-egg-info-jqpacssm
    running egg_info
    creating C:\Users\s147569\AppData\Local\Temp\pip-pip-egg-info-jqpacssm\infomap.egg-info
    writing C:\Users\s147569\AppData\Local\Temp\pip-pip-egg-info-jqpacssm\infomap.egg-info\PKG-INFO
    writing dependency_links to C:\Users\s147569\AppData\Local\Temp\pip-pip-egg-info-jqpacssm\infomap.egg-info\dependency_links.txt
    writing entry points to C:\Users\s147569\AppData\Local\Temp\pip-pip-egg-info-jqpacssm\infomap.egg-info\entry_points.txt
    writing top-level names to C:\Users\s147569\AppData\Local\Temp\pip-pip-egg-info-jqpacssm\infomap.egg-info\top_level.txt
    writing manifest file 'C:\Users\s147569\AppData\Local\Temp\pip-pip-egg-info-jqpacssm\infomap.egg-info\SOURCES.txt'
    reading manifest file 'C:\Users\s147569\AppData\Local\Temp\pip-pip-egg-info-jqpacssm\infomap.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'C:\Users\s147569\AppData\Local\Temp\pip-pip-egg-info-jqpacssm\infomap.egg-info\SOURCES.txt'
  Source in c:\users\s147569\appdata\local\temp\pip-req-build-zjneawaa has version 1.1.3, which satisfies requirement infomap==1.1.3 from file:///C:/ProgramData/Anaconda3/conda-bld/infomap_1595497087882/work
  Removed infomap==1.1.3 from file:///C:/ProgramData/Anaconda3/conda-bld/infomap_1595497087882/work from build tracker 'C:\\Users\\s147569\\AppData\\Local\\Temp\\pip-req-tracker-3hlurgau'
Building wheels for collected packages: infomap
  Created temporary directory: C:\Users\s147569\AppData\Local\Temp\pip-wheel-xme9chd5
  Building wheel for infomap (setup.py): started
  Destination directory: C:\Users\s147569\AppData\Local\Temp\pip-wheel-xme9chd5
  Running command 'C:\ProgramData\Anaconda3\conda-bld\infomap_1595497087882\_h_env\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\s147569\\AppData\\Local\\Temp\\pip-req-build-zjneawaa\\setup.py'"'"'; __file__='"'"'C:\\Users\\s147569\\AppData\\Local\\Temp\\pip-req-build-zjneawaa\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\s147569\AppData\Local\Temp\pip-wheel-xme9chd5'
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  copying infomap.py -> build\lib.win-amd64-3.7
  copying package_meta.py -> build\lib.win-amd64-3.7
  running egg_info
  writing infomap.egg-info\PKG-INFO
  writing dependency_links to infomap.egg-info\dependency_links.txt
  writing entry points to infomap.egg-info\entry_points.txt
  writing top-level names to infomap.egg-info\top_level.txt
  reading manifest file 'infomap.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'infomap.egg-info\SOURCES.txt'
  running build_ext
  building '_infomap' extension
  creating build\temp.win-amd64-3.7
  creating build\temp.win-amd64-3.7\Release
  creating build\temp.win-amd64-3.7\Release\src
  creating build\temp.win-amd64-3.7\Release\src\core
  creating build\temp.win-amd64-3.7\Release\src\io
  creating build\temp.win-amd64-3.7\Release\src\utils
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\bin\Hostx64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iheaders -Iheaders/src -Iheaders/src/core -Iheaders/src/io -Iheaders/src/utils -IC:\ProgramData\Anaconda3\conda-bld\infomap_1595497087882\_h_env\include -IC:\ProgramData\Anaconda3\conda-bld\infomap_1595497087882\_h_env\include -IC:\ProgramData\Anaconda3\conda-bld\infomap_1595497087882\_h_env\Library\include /EHsc /Tp./infomap_wrap.cpp /Fobuild\temp.win-amd64-3.7\Release\./infomap_wrap.obj /DAS_LIB /DPYTHON /DNOMINMAX
  infomap_wrap.cpp
  C:\ProgramData\Anaconda3\conda-bld\infomap_1595497087882\_h_env\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.25.28610\\bin\\Hostx64\\x64\\cl.exe' failed with exit status 2
  Building wheel for infomap (setup.py): finished with status 'error'
  ERROR: Failed building wheel for infomap
  Running setup.py clean for infomap
  Running command 'C:\ProgramData\Anaconda3\conda-bld\infomap_1595497087882\_h_env\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\s147569\\AppData\\Local\\Temp\\pip-req-build-zjneawaa\\setup.py'"'"'; __file__='"'"'C:\\Users\\s147569\\AppData\\Local\\Temp\\pip-req-build-zjneawaa\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
  running clean
  removing 'build\temp.win-amd64-3.7' (and everything under it)
  removing 'build\lib.win-amd64-3.7' (and everything under it)
  'build\bdist.win-amd64' does not exist -- can't clean it
  'build\scripts-3.7' does not exist -- can't clean it
  removing 'build'
Failed to build infomap
Installing collected packages: infomap
  Created temporary directory: C:\Users\s147569\AppData\Local\Temp\pip-record-tcick1od
    Running command 'C:\ProgramData\Anaconda3\conda-bld\infomap_1595497087882\_h_env\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\s147569\\AppData\\Local\\Temp\\pip-req-build-zjneawaa\\setup.py'"'"'; __file__='"'"'C:\\Users\\s147569\\AppData\\Local\\Temp\\pip-req-build-zjneawaa\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\s147569\AppData\Local\Temp\pip-record-tcick1od\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\ProgramData\Anaconda3\conda-bld\infomap_1595497087882\_h_env\Include\infomap'
    Running setup.py install for infomap: started
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    copying infomap.py -> build\lib.win-amd64-3.7
    copying package_meta.py -> build\lib.win-amd64-3.7
    running egg_info
    writing infomap.egg-info\PKG-INFO
    writing dependency_links to infomap.egg-info\dependency_links.txt
    writing entry points to infomap.egg-info\entry_points.txt
    writing top-level names to infomap.egg-info\top_level.txt
    reading manifest file 'infomap.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'infomap.egg-info\SOURCES.txt'
    running build_ext
    building '_infomap' extension
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\src
    creating build\temp.win-amd64-3.7\Release\src\core
    creating build\temp.win-amd64-3.7\Release\src\io
    creating build\temp.win-amd64-3.7\Release\src\utils
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\bin\Hostx64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iheaders -Iheaders/src -Iheaders/src/core -Iheaders/src/io -Iheaders/src/utils -IC:\ProgramData\Anaconda3\conda-bld\infomap_1595497087882\_h_env\include -IC:\ProgramData\Anaconda3\conda-bld\infomap_1595497087882\_h_env\include -IC:\ProgramData\Anaconda3\conda-bld\infomap_1595497087882\_h_env\Library\include /EHsc /Tp./infomap_wrap.cpp /Fobuild\temp.win-amd64-3.7\Release\./infomap_wrap.obj /DAS_LIB /DPYTHON /DNOMINMAX
    infomap_wrap.cpp
    C:\ProgramData\Anaconda3\conda-bld\infomap_1595497087882\_h_env\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.25.28610\\bin\\Hostx64\\x64\\cl.exe' failed with exit status 2
    Running setup.py install for infomap: finished with status 'error'
ERROR: Command errored out with exit status 1: 'C:\ProgramData\Anaconda3\conda-bld\infomap_1595497087882\_h_env\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\s147569\\AppData\\Local\\Temp\\pip-req-build-zjneawaa\\setup.py'"'"'; __file__='"'"'C:\\Users\\s147569\\AppData\\Local\\Temp\\pip-req-build-zjneawaa\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\s147569\AppData\Local\Temp\pip-record-tcick1od\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\ProgramData\Anaconda3\conda-bld\infomap_1595497087882\_h_env\Include\infomap' Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "%PREFIX%\lib\site-packages\pip\_internal\req\req_install.py", line 841, in install
    req_description=str(self.req),
  File "%PREFIX%\lib\site-packages\pip\_internal\operations\install\legacy.py", line 86, in install
    raise LegacyInstallFailure
pip._internal.operations.install.legacy.LegacyInstallFailure

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "%PREFIX%\lib\site-packages\pip\_internal\cli\base_command.py", line 188, in _main
    status = self.run(options, args)
  File "%PREFIX%\lib\site-packages\pip\_internal\cli\req_command.py", line 185, in wrapper
    return func(self, options, args)
  File "%PREFIX%\lib\site-packages\pip\_internal\commands\install.py", line 407, in run
    use_user_site=options.use_user_site,
  File "%PREFIX%\lib\site-packages\pip\_internal\req\__init__.py", line 71, in install_given_reqs
    **kwargs
  File "%PREFIX%\lib\site-packages\pip\_internal\req\req_install.py", line 845, in install
    six.reraise(*exc.parent)
  File "%PREFIX%\lib\site-packages\pip\_vendor\six.py", line 703, in reraise
    raise value
  File "%PREFIX%\lib\site-packages\pip\_internal\operations\install\legacy.py", line 76, in install
    cwd=unpacked_source_directory,
  File "%PREFIX%\lib\site-packages\pip\_internal\utils\subprocess.py", line 274, in runner
    spinner=spinner,
  File "%PREFIX%\lib\site-packages\pip\_internal\utils\subprocess.py", line 241, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: '%PREFIX%\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\s147569\\AppData\\Local\\Temp\\pip-req-build-zjneawaa\\setup.py'"'"'; __file__='"'"'C:\\Users\\s147569\\AppData\\Local\\Temp\\pip-req-build-zjneawaa\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\s147569\AppData\Local\Temp\pip-record-tcick1od\install-record.txt' --single-version-externally-managed --compile --install-headers '%PREFIX%\Include\infomap' Check the logs for full command output.
Removed build tracker: 'C:\\Users\\s147569\\AppData\\Local\\Temp\\pip-req-tracker-3hlurgau'
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\conda-build-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda_build\cli\main_build.py", line 469, in main
    execute(sys.argv[1:])
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda_build\cli\main_build.py", line 460, in execute
    verify=args.verify, variants=args.variants)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda_build\api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda_build\build.py", line 2344, in build_tree
    notest=notest,
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda_build\build.py", line 1459, in build
    windows.build(m, build_file, stats=build_stats, provision_only=provision_only)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda_build\windows.py", line 294, in build
    check_call_env(cmd, cwd=m.config.work_dir, stats=stats, rewrite_stdout_env=rewrite_env)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda_build\utils.py", line 398, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda_build\utils.py", line 378, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['cmd.exe', '/d', '/c', 'conda_build.bat']' returned non-zero exit status 1.
```

**Comment by antoneri** [comment]
Hi and thanks for reaching out!

The conda package is not maintained by us unfortunately. I'd like to help you more, but I need to reproduce the results. 

Perhaps @danieledler knows more about Windows installations?
