### ISSUE TITLE
install issue on windows10

### ISSUE THREAD

**Issue by superhy** [mapequation/infomap#217]
```
ERROR: Command errored out with exit status 1:
     command: 'D:\ProgramData\Anaconda3\envs\python37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\super\\AppData\\Local\\Temp\\pip-install-1wb9_9ya\\infomap_ad17e3f4f6524ec197364033b4aa2409\\setup.py'"'"'; __file__='"'"'C:\\Users\\super\\AppData\\Local\\Temp\\pip-install-1wb9_9ya\\infomap_ad17e3f4f6524ec197364033b4aa2409\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\super\AppData\Local\Temp\pip-pip-egg-info-jkrqpxcl'
         cwd: C:\Users\super\AppData\Local\Temp\pip-install-1wb9_9ya\infomap_ad17e3f4f6524ec197364033b4aa2409\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\super\AppData\Local\Temp\pip-install-1wb9_9ya\infomap_ad17e3f4f6524ec197364033b4aa2409\setup.py", line 97, in <module>
        if have_openmp():
      File "C:\Users\super\AppData\Local\Temp\pip-install-1wb9_9ya\infomap_ad17e3f4f6524ec197364033b4aa2409\setup.py", line 45, in have_openmp
        compiler = get_compiler()
      File "C:\Users\super\AppData\Local\Temp\pip-install-1wb9_9ya\infomap_ad17e3f4f6524ec197364033b4aa2409\setup.py", line 18, in get_compiler
        return os.environ.get('CXX', get_config_var('CXX')).split()[0]
    AttributeError: 'NoneType' object has no attribute 'split'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by antoneri** [comment]
Thanks for reaching out!

The fix will be available soon on PyPi.
