### ISSUE TITLE
Can't import infomap into python 2.7.12

### ISSUE THREAD

**Issue by dharif23** [mapequation/infomap#24]
```Python
Python 2.7.12 (default, Dec  4 2017, 14:50:18)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import infomap
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/infomap.py", line 468
    def cloneAsNonMain(self, other: 'Config') -> "infomap::Config &":
                                  ^
SyntaxError: invalid syntax
>>>
```
System: Linux Mint 18.3

**Comment by danieledler** [comment]
Installation should work now with python2 also (version 1.0.0-beta.8), though there seem to be some incompatibility in the iteration wrapper code for python2. If you also get that, please open a new issue.
