### ISSUE TITLE
Issue with installation on Windows

### ISSUE THREAD

**Issue by panfinik** [mapequation/infomap#357]
Hi, 

tried to install infomap on Windows 11 using pip, but every time has strange issue. I updated python and checked everything about python setting but it didn't work out/

Or is it issue with anaconda?
  error: subprocess-exited-with-error
  
  python setup.py egg_info did not run successfully.
  exit code: 1
  
  [26 lines of output]
  C:\RTemp\pip-install-kjma5wkr\infomap_f307763a72294b7ba0f34a95728bc93c\setup.py:13: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    from pkg_resources import parse_version
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\RTemp\pip-install-kjma5wkr\infomap_f307763a72294b7ba0f34a95728bc93c\setup.py", line 131, in <module>
      if have_openmp():
         ^^^^^^^^^^^^^
    File "C:\RTemp\pip-install-kjma5wkr\infomap_f307763a72294b7ba0f34a95728bc93c\setup.py", line 67, in have_openmp
      if is_clang():
         ^^^^^^^^^^
    File "C:\RTemp\pip-install-kjma5wkr\infomap_f307763a72294b7ba0f34a95728bc93c\setup.py", line 25, in is_clang
      return b"clang" in subprocess.check_output([get_compiler(), "--version"])
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\ProgramData\anaconda3\Lib\subprocess.py", line 466, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\ProgramData\anaconda3\Lib\subprocess.py", line 548, in run
      with Popen(*popenargs, **kwargs) as process:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\ProgramData\anaconda3\Lib\subprocess.py", line 1026, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "C:\ProgramData\anaconda3\Lib\subprocess.py", line 1538, in _execute_child
      hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  FileNotFoundError: [WinError 2] The system cannot find the file specified
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by noblefairytale** [comment]
I have the same error, interested if anyone finds a solution to fix this.

**Comment by a641324093** [comment]
me too

**Comment by 1ines** [comment]
I have similar issue on Linux

**Comment by pinkskyxj** [comment]
I have the same issue on win10

**Comment by pinkskyxj** [comment]
> I have the same issue on win10

ok,I have solved this problem.My python version is 3.11,but infomap just support py3.6 to 3.10.After I download and install python3.8,I can download infomap on Navigator(search 'infomap' then apply).Finally,it works.

**Comment by SAIL-Fang** [comment]
> > I have the same issue on win10
> 
> ok,I have solved this problem.My python version is 3.11,but infomap just support py3.6 to 3.10.After I download and install python3.8,I can download infomap on Navigator(search 'infomap' then apply).Finally,it works.

Time to install conda😭

**Comment by ttimasdf** [comment]
The CI [release workflow](https://github.com/mapequation/infomap/blob/master/.github/workflows/python-publish.yml) currently builds wheels only for Python versions 3.7 to 3.10. Python 3.7 reached [end-of-life five years ago](https://en.wikipedia.org/wiki/History_of_Python#Table_of_versions), and support for Python 3.10 ended in 2023. It is recommended to update the build workflow if there are no known issues with newer Python versions. @danieledler

For those seeking a quick and simple workaround, a GCC compiler is required on Windows to build from the Infomap source distribution. Installing MSYS2 is recommended, as it provides a complete GNU toolchain, which can be useful for other projects.

```pwsh
# Install MSYS2 if not already installed
winget install MSYS2.MSYS2

# In MSYS2 UCRT64 shell
pacman -S mingw-w64-ucrt-x86_64-toolchain mingw-w64-ucrt-x86_64-cmake mingw-w64-ucrt-x86_64-make
pip wheel infomap
```

This will generate `infomap-2.8.0-cp313-cp313-win_amd64.whl` in the current directory. You can install this wheel in other virtual environments, and it is also compatible with `uv pip`.
