### ISSUE TITLE
infomap python install issue

### ISSUE THREAD

**Issue by jokedurnez** [mapequation/infomap#8]
Hi,

I have been able to install succesfully infomap (with python wrapper) on my cluster environment.  When I try to install it on my local (OSX) machine, I get the following error when installing the python wrapper:

```
g++ -bundle -undefined dynamic_lookup -L/Users/Joke/anaconda/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.7-x86_64-2.7/./infomap_wrap.o build/temp.macosx-10.7-x86_64-2.7/./src/Infomap.o build/temp.macosx-10.7-x86_64-2.7/./src/infomap/FlowNetwork.o build/temp.macosx-10.7-x86_64-2.7/./src/infomap/InfomapBase.o build/temp.macosx-10.7-x86_64-2.7/./src/infomap/InfomapContext.o build/temp.macosx-10.7-x86_64-2.7/./src/infomap/MemFlowNetwork.o build/temp.macosx-10.7-x86_64-2.7/./src/infomap/MemNetwork.o build/temp.macosx-10.7-x86_64-2.7/./src/infomap/MemoryNetworkAdapter.o build/temp.macosx-10.7-x86_64-2.7/./src/infomap/MultiplexNetwork.o build/temp.macosx-10.7-x86_64-2.7/./src/infomap/Network.o build/temp.macosx-10.7-x86_64-2.7/./src/infomap/NetworkAdapter.o build/temp.macosx-10.7-x86_64-2.7/./src/infomap/Node.o build/temp.macosx-10.7-x86_64-2.7/./src/infomap/TreeData.o build/temp.macosx-10.7-x86_64-2.7/./src/io/BipartiteClusterReader.o build/temp.macosx-10.7-x86_64-2.7/./src/io/ClusterReader.o build/temp.macosx-10.7-x86_64-2.7/./src/io/HierarchicalNetwork.o build/temp.macosx-10.7-x86_64-2.7/./src/io/ProgramInterface.o build/temp.macosx-10.7-x86_64-2.7/./src/io/TreeDataWriter.o build/temp.macosx-10.7-x86_64-2.7/./src/io/version.o build/temp.macosx-10.7-x86_64-2.7/./src/utils/FileURI.o build/temp.macosx-10.7-x86_64-2.7/./src/utils/Logger.o -L/Users/Joke/anaconda/lib -o /Users/Joke/Documents/Onderzoek/Stanford/RandomNotes/infomap/build/py/_infomap.so
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9
Traceback (most recent call last):
  File "setup.py", line 44, in <module>
    copy_file(libFilename, '_infomap.so')
  File "/Users/Joke/anaconda/lib/python2.7/distutils/file_util.py", line 110, in copy_file
    "can't copy '%s': doesn't exist or not a regular file" % src)
distutils.errors.DistutilsFileError: can't copy '_infomapNone': doesn't exist or not a regular file
make[1]: *** [python] Error 1
make: *** [../../build/py/infomap.py] Error 2
```

**Comment by danieledler** [comment]
Hi,

I haven't been able to test this as I didn't have the problem on my local OS X machine, so please confirm if it solves your problem.
